### ISSUE TITLE
Add the synology installer to SynoCommunity repo.

### ISSUE THREAD

**Issue by M0UL** [ukdtom/WTInstaller#16]
is posible to add the synology installer to SynoCommunity repo for automatic updates.
https://github.com/SynoCommunity/spksrc

**Comment by ukdtom** [comment]
It's a one time installer.....

After it has installed WebTools, WebTools itself can update.

But regardless, it'll be one Q for @ChuckPa to answer

**Comment by ChuckPa** [comment]
Syno Community requires all additions to use spksrc, which as you know is getting a lot of attention thanks to DSM 6 changes.   Everyone there is overloaded fixing the existing packages.

When the load settles down,  I can bring it up to them with the understanding it is indeed a 1-time installer and does not require spksrc.  They may grant a waiver.

**Comment by ChuckPa** [comment]
Went ahead and submitted it.  We will see what happens.
