### ISSUE TITLE
Cannot access the :33400 site

### ISSUE THREAD

**Issue by sikman1** [ukdtom/WTInstaller#17]
Hi, great tool, but if I run the WT install app on the QNAP a new browser tab opens and tries to go to the :33400 site. But I get a a message that I am not allowed to access the site. Any idea what goes wrong? Thanks!

**Comment by ukdtom** [comment]
Go to `<IP of QNAP>:32400/web`

**Comment by sikman1** [comment]
Sorry, this brings me to the standard PLEX webinterface, not the site were I can install the WebTools.

**Comment by sikman1** [comment]
Maybe I wasn't clear, the issue is not opening the PLEX mediaserver, the isse is that I cannot access the website to install te WebTools.

**Comment by Laim** [comment]
I'm having this issue at the moment as well. It worked first time, went to go into it again today and it told me it couldn't access the site. 

Everything else works, just not WT. 

Going to try a re-install and see what it does. 

Edit:

Tried to reinstall, but throwing the same (http://i.imgur.com/ZKhISWh.png).

**Comment by sikman1** [comment]
For me the issue magically disappeared after updating the Plex Media Server to the latest version.

**Comment by ukdtom** [comment]
@Laim 

First of all sorry by the delay responding here, but been sidetracked by other dev stuff

Please grab the WebTools log files, as well as provide info about PMS platform, but assume it's a Mac ?

**Comment by ukdtom** [comment]
Closing, since OP has this fixed, and others not responding

**Comment by Laim** [comment]
@ukdtom apologizes. I forgot I even commented here, it was QNAP, I had to reboot my entire device twice and it started working again, so I assume it was a user related issue and not the actual plugin.
