### ISSUE TITLE
"Unable to Connect" when attempting to access 33400

### ISSUE THREAD

**Issue by genx777** [ukdtom/WTInstaller#19]
I unfortunately had to get a new system, and upon re-installing Plex and setting it back up, I had a problem accessing the interface via the 33400 port with the webtools bundle.  

I've tried several browsers, as well as restarting the PMS, etc.  

I'm running Windows 10, 64 Bit.  Any suggestions?

Thanks!

GenX

**Comment by haxcop** [comment]
I Got this same issue after update webtools.

**Comment by ukdtom** [comment]
I need WebTools Logs from both of you!

**Comment by genx777** [comment]
Evening, guys.  I was actually able to resolve my issue today with the installer.  Hax-- if you are trying to use the 2.1 bundle and manually install it, try the Windows Installer located on ukdtom's page instead.  That worked like a charm for me.

Thanks, ukdtom, for your contributions!

**Comment by ukdtom** [comment]
You're welcome, and FUI, 2.1 version is very old!
