### ISSUE TITLE
No access 33400

### ISSUE THREAD

**Issue by w3st09** [ukdtom/WTInstaller#20]
Installed WebTools via WTinstaller 2.4.1 successfully and run it but there is no access to 33400.
Sinology DSM 6.1.1-15101 Update 4
Plex:  1.5.3.3580
WebTools: 1.4

Here's the WebTool.log
2017-05-31 09.30.05 EDT: Updating from https://api.github.com/repos/ukdtom/WebTools.bundle/tarball/2.4.1
2017-05-31 09.30.06 EDT: Download successful. Proceeding with installation.
2017-05-31 09.30.06 EDT: WebTools installation complete.
2017-05-31 09.30.06 EDT:
2017-05-31 09.30.07 EDT: Started

**Comment by ukdtom** [comment]
Did you make exceptions in the firewall for port 33400 and 33443?

**Comment by w3st09** [comment]
There is no firewall enabled in the DSM (snapshot attached).
Please advise if there is anything else to be done via cli.
<img width="778" alt="1" src="https://cloud.githubusercontent.com/assets/29098414/26662575/d725d484-4652-11e7-89c4-903bf5482f1d.png">

**Comment by ukdtom** [comment]
Then I need WebTools log files
https://support.plex.tv/hc/en-us/articles/200250417-Log-File-Locations

**Comment by w3st09** [comment]
I've looked at /Plex/Library/Application Support/Plex Media Server/Logs/ but I can'e see WebTools log files... take a look at the screenshots and let me know if you see them or if you need me to send some of the log files you see.

<img width="995" alt="2" src="https://cloud.githubusercontent.com/assets/29098414/26686913/6b3d8d06-46bc-11e7-92dd-f022b24cd98f.png">

<img width="975" alt="3" src="https://cloud.githubusercontent.com/assets/29098414/26686918/6e7bad0e-46bc-11e7-9d99-86deb602446d.png">

**Comment by ukdtom** [comment]
Seems like WebTools isn't installed at all.
Could you show a screendump of the Plug-ins directory, and if a webtools.bundle dir is persent in that, then also a dump of that directory

**Comment by w3st09** [comment]
It is installed in that Plug-ins directory. Take a look at the screenshot. Attached is a zip with all the content of the Plug-ins directory where there is a WebTool.log file the contain of which I already posted in the beginning:

2017-05-31 09.30.05 EDT: Updating from https://api.github.com/repos/ukdtom/WebTools.bundle/tarball/2.4.1
2017-05-31 09.30.06 EDT: Download successful. Proceeding with installation.
2017-05-31 09.30.06 EDT: WebTools installation complete.
2017-05-31 09.30.06 EDT:
2017-05-31 09.30.07 EDT: Started

<img width="976" alt="4" src="https://cloud.githubusercontent.com/assets/29098414/26693618/cc43d7ac-46d2-11e7-8361-98e24d153b82.png">

[WebTools.zip](https://github.com/ukdtom/WTInstaller/files/1045652/WebTools.zip)

**Comment by ukdtom** [comment]
@ChuckPa Care to step in here?

**Comment by ChuckPa** [comment]
As general diagnosis,   I do my best to detect all possible errors from github but is is possible (unlikely but possible) to get a bad download.

Have you attempted to uninstall it and reinstall it?

**Comment by w3st09** [comment]
I did reinstall it many times. with and without Plex runing and restarting plex after WT install.
I've checked it with all major browsers. i can provide any output from cli if you need.
Thanks!

**Comment by WeeHannah** [comment]
I ran into this problem. Resolved it by going into the plugin folder in Plex where I had tried to manually install webtools previously. I deleted this folder and the installation went ahead.
