### ISSUE TITLE
Please update to version 3.0.0

### ISSUE THREAD

**Issue by TheBlackBush** [ukdtom/WTInstaller#22]
Can you please update the easy installer for Synology (and the others) to version 3.0.0?

Thank,
Idan

**Comment by ukdtom** [comment]
Just run it again, and it should download the latest

**Comment by TheBlackBush** [comment]
It doesn’t download the new version, there is a message that won’t come off when login.
It’s says that I need to install it manually.

![2cc80589-3e59-4415-9e22-677d004e832d](https://user-images.githubusercontent.com/1271474/33852550-a7c8d362-dec3-11e7-8b83-5df15e4a54e8.png)

**Comment by ukdtom** [comment]
I've assigned the developer of the Synology installer

**Comment by TheBlackBush** [comment]
Nevermind, i just reinstalled it and it pulled the latest version.

Thanks...
