### ISSUE TITLE
Can't sign in if Google Identity used for Plex account

### ISSUE THREAD

**Issue by abear1538** [ukdtom/WTInstaller#25]
When opening WebTools I'm prompted to sign in, but where's the option to log in with my Google account?

I've signed in to Plex with Google, so I don't have a Plex-specific username and password...

**Comment by abear1538** [comment]
Nevermind, I figured it out:

If you go into Settings > Account you can create a username and password even if you used Google Identity Platform to register your account.

**Comment by ukdtom** [comment]
And for others reading this, check Q8 in WebTools FAQ
https://github.com/ukdtom/WebTools.bundle/wiki/FAQ
