### ISSUE TITLE
playlists copied dont retain show postitioning

### ISSUE THREAD

**Issue by weasel18** [ukdtom/WTInstaller#26]
A couple of my playlists I've copied to another user won't keep the positioning of the movies/ tv-shows in that playlist. and it doesn't seem to really be sorting it by any order particularly just randomly. This is an issue because im building a marvel playlist and every movie is a different time line, and on my main playlist its in the order i want it

**Comment by ukdtom** [comment]
Firstly you created this issue in the installer git, not in WT git itself

And secondly, development has stopped for WebTools
