### ISSUE TITLE
WebTool don't open after 3 reboot and instalation

### ISSUE THREAD

**Issue by Kiana321** [ukdtom/WTInstaller#29]
Dear,

I can't open WebTool on : http://192.168.1.160:33400/

I have reboot Qnap Server 3 time and reinstalle WebTool 3 time.

I can't delete WebTool in Plex directly and when I want change setting that load infinite time as well : 
![image](https://user-images.githubusercontent.com/97845594/149670007-0ca2dd2f-3a28-4862-adc0-df8a9ef580ca.png)

How can I solve this solution ? I think that from port direction I think it's assignate at 32400 same port of Plex server

**Comment by ukdtom** [comment]
See: https://github.com/ukdtom/WebTools.bundle/wiki/Reset

And since not an installer issue, I'll close this

Do use the forum thread, as I already told you

https://forums.plex.tv/t/rel-webtools-unsupported-appstore/206843
