### ISSUE TITLE
QNAP package fails signature check

### ISSUE THREAD

**Issue by fauxserve** [ukdtom/WTInstaller#30]
The instructions do not provide hints either way if the package is signed or not, or to change security settings if needed, so I assume it should be signed. When trying to install, I get this error:

`Error	2022-05-09	13:31:25	System	127.0.0.1	App Center	App Installation	[App Center] Failed to install QNAP-WT-Install. The digital signature is invalid. To proceed with installation, go to App Center > Settings > General, and then select "Allow installation of applications without a valid digital signature".`

![Screen Shot 2022-05-09 at 1 33 08 PM](https://user-images.githubusercontent.com/15825721/167493295-2ad23c8d-0b5e-4b86-b37f-d1288dae1e53.png)

**Comment by ukdtom** [comment]
Correct, it was an oldie from before QNAP req. signed qpkg's

We'll not change this, since WebTools.bundle development has stopped anyway

To install regardless, go here:

![image](https://user-images.githubusercontent.com/4699449/167499962-76e408dc-fd5a-47be-bb52-fcb7ed9f6a78.png)
